// docs/src/components/SingleVerticalListWithAutoscroll.vue
<script setup lang="ts">
import { ref } from "vue";
import { useDragAndDrop } from "vue-fluid-dnd";

const list = ref([...Array(20).keys()]);
const { parent } = useDragAndDrop(list);
</script>
<template>
  <ul ref="parent" class="number-list">
    <li class="number" v-for="(element, index) in list" :index="index">
      {{ element }}
    </li>
  </ul>
</template>

<style>
.number {
  border-style: solid;
  margin-top: 0.25rem;
  border-width: 2px;
  border-color: var(--sl-color-gray-1);
}
.number-list {
  display: block;
  padding-inline: 10px;
  overflow-y: auto;
  width: 80%;
  height: 300px;
  padding-left: 30px;
}
.temp-child {
  margin-top: 0 !important;
}
</style>

// docs/src/components/svelte/SingleVerticalListWithAutoscroll.svelte
<script lang="ts">
    import { useDragAndDrop } from "fluid-dnd/svelte";
    
    const list = $state([...Array(20).keys()]);
    const [ parent ] = useDragAndDrop(list);
</script>
<ul use:parent class="block px-2 overflow-y-auto w-10/12 h-80 pl-7">
    {#each list as element, index }
        <li class="solid mt-1 border-2" data-index = {index}>
            { element }
        </li>
    {/each }
</ul>
<style>
    :global(.temp-child){
      margin-top: 0 !important;
    }
</style>
