// docs/src/components/examples/svelte/SingleVerticalListOfPokemons.svelte
<script lang="ts">
    import { useDragAndDrop } from "fluid-dnd/svelte";
    import type { Pokemon } from "../Pokemon";
    import PokemonComponent from "./PokemonComponent.svelte";
    import { fetchPokemons } from "@/server/pokemonServer";
    
    let pokemons = $state([] as Pokemon[]);
    fetchPokemons(9).then((newPokemons) => {
        pokemons.push(...newPokemons);
    });
    const [ parent ] = useDragAndDrop(pokemons, {
      draggingClass: "dragging-pokemon",
    });
</script>
<div class="flex max-sm:justify-center items-start">
  <div
    use:parent
    class="bg-gray-200/60 border-solid border-black/40 rounded-2xl w-60 border-4 p-4 block"
  >
  {#each pokemons as pokemon, index (pokemon.name)}
    <PokemonComponent
      index={index}
      pokemon={pokemon}
    />
  {/each}
  </div>
</div>
<style>
  :global(.sl-markdown-content
    :not(a, strong, em, del, span, input, code)
    + :not(a, strong, em, del, span, input, code, :where(.not-content *))) {
    margin-top: 0rem !important;
  }
</style>

// docs/src/components/examples/SingleVerticalListOfPokemons.vue
<script setup lang="ts">
import { ref } from "vue";
import { useDragAndDrop } from "vue-fluid-dnd";
import type { Pokemon } from "./Pokemon";
import PokemonComponent from "./PokemonComponent.vue";
import { fetchPokemons } from "@/server/pokemonServer";

const pokemons = ref([] as Pokemon[]);
pokemons.value = await fetchPokemons(9);
const { parent } = useDragAndDrop(pokemons);
</script>
<template>
  <div class="flex justify-center items-start">
    <div
      ref="parent"
      class="bg-gray-200/60 border-solid border-black/40 rounded-2xl w-60 border-4 p-4 block"
    >
      <PokemonComponent
        v-for="(pokemon, index) in pokemons"
        :key="pokemon.name"
        :index="index"
        :pokemon="pokemon"
      />
    </div>
  </div>
</template>
<style>
.sl-markdown-content
  :not(a, strong, em, del, span, input, code)
  + :not(a, strong, em, del, span, input, code, :where(.not-content *)) {
  margin-top: 0rem !important;
}
</style>
